version: "3.9"
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - ${SEQUELIZE_PORT}:${SEQUELIZE_PORT}
    environment:
      - MYSQL_DATABASE=${SEQUELIZE_DB}
      - MYSQL_USER=${SEQUELIZE_USERNAME}
      - MYSQL_PASSWORD=${SEQUELIZE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${SEQUELIZE_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --appendonly yes 
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis_data:/data

  app:
    build:
      context: /root/bma-api
    container_name: app
    environment:
      - NODE_ENV=localhost
      - REDIS_URL=${REDIS_DOCKER_URL}
      - DATABASE_URL=mysql://${SEQUELIZE_USERNAME}:${SEQUELIZE_PASSWORD}@mysql:3306/${SEQUELIZE_DB}
    restart: always
    volumes:
      - /app
      - /app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - mysql
      - redis

  nginx:
    build: ./nginx
    container_name: nginx_load_balancer
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - mysql
      - redis
      - app

volumes:
  redis_data:
  mysql_data:
